theme = "dracula"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["version-control", "selections", "total-line-numbers", "position"]

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[keys.insert]
"C-;" = "normal_mode"

[keys.select]
"C-;" = "normal_mode"

[keys.normal.g]
a = "code_action"
